language: python
python:
#  - "2.6"
#  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
# command to install dependencies
install: "python3 setup.py install" 
# command to run tests
before_script:
- pip3 install py.test
- pip3 install pytest-cov
script: py.test --cov-report --cov=phone2address
